### ISSUE TITLE
configurable certificate? 

### ISSUE THREAD

**Issue by rusenask** [elazarl/goproxy#146]
Hey,
Not sure if it's only me, but I think it would be nice to pass your own certificate to goproxy for https mitm. I could make a PR for this.

Cheers

**Comment by elazarl** [comment]
You can already do that.

Easiest route is to change the global `GoproxyCa` variable.

For more complex scenerios:

Instead of `AlwaysMitm`, use your own `ConnectAction`, where you'll put your own 
See https://github.com/elazarl/goproxy/blob/master/https.go#L354

I'm unfortunately not having enough time at the moment, but I'd love to accept a PR for an example of using a custom CA.

**Comment by elazarl** [comment]
@rusenask let me know if you got it, if you still have problems I'll try to write more.
