### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by qZanity** [elazarl/goproxy#273]
Hello, When running 500+ concurrent connections I get the following error.

> http: Accept error: accept tcp [::]:9995: accept4: too many open files; retrying in 

My server is setup to 100k connections using "ulimit -n", i have increased both hard and softlimits for "nofile" 

I have also increased the proxy.Tr.MaxIdleConns, but the problem is still occuring.

There seems to be an old issue that was fixed without explanation here #75 

Any help is welcome.

**Comment by lamg** [comment]
Checkout this https://blog.cloudflare.com/the-complete-guide-to-golang-net-http-timeouts/

**Comment by unkaktus** [comment]
I had the same bug - it wasn't in goproxy but in the way I used it. I was creating new proxy instance on each incoming connection, and because goproxy creates a pool of persistent connections, their number grows eventually hitting the fd limit. It is very likely you have the same bug in your code. 😉 
Well, we all were 5 years younger back then, eh!

**Comment by ErikPelli** [comment]
This issue is not related to goproxy but it's caused by the user code, according to the users replies
