### ISSUE TITLE
Allow non-cannonical headers

### ISSUE THREAD

**Issue by physics-sec** [elazarl/goproxy#403]
Hi!
When you copy the headers, using `copyHeaders` [here](https://github.com/elazarl/goproxy/blob/master/proxy.go#L38-L49), you use the `Add` method, which is defined [here](https://golang.org/src/net/http/header.go) (line 27).  

The "issue" is that `Add` canonicalizes the the headers as explained [here](https://golang.org/pkg/net/textproto/#CanonicalMIMEHeaderKey).  
This is fine for the most part, but it would be really cool to allow non-cannonical headers by passing some flag to the proxy initialization.  

In order to do that, instead of using `Add` or `Set`, assign to the map directly. As stated [here](https://golang.org/src/net/http/header.go) (line 35).  

I hope you would consider it.  
Thank you!

**Comment by alfonso-presa** [comment]
Hi. I would also like to see this happening. We have some third-party client libraries that are not tolerant to case change in headers (I know that is wrong, as per the HTTP specification, they should not rely in case). Would you consider a PR for this?

Thanks!

**Comment by elazarl** [comment]
Sure, would be happy for a PR

**Comment by alfonso-presa** [comment]
Hi @elazarl,

trying to change this, the issue is not in the Add inside goproxy but on the httpclient itself that is making the header names cannonical. So that has to be fixed before changing goproxy behaviour.... and it doesn't seem to be happening in the sort term: https://github.com/golang/go/issues/37834
