### ISSUE TITLE
r.Form.Set not working

### ISSUE THREAD

**Issue by bagwaa** [elazarl/goproxy#98]
I have managed to implement goProxy with the `r.Headers.Set` correctly, when I try to do the same with `r.Form.Set` the form post variables are not added as expected?

I have included a sample snippet

``` go
package main

import (
    "net/http"

    "github.com/elazarl/goproxy"
)

func main() {
    proxy := goproxy.NewProxyHttpServer()
    proxy.Verbose = true

    proxy.OnRequest().DoFunc(
        func(r *http.Request, ctx *goproxy.ProxyCtx) (*http.Request, *http.Response) {
            r.ParseForm()
            r.Form.Set("Foo", "Bar")
            return r, nil
        })

    http.ListenAndServe(":8081", proxy)
}
```

**Comment by elazarl** [comment]
Hi,

Form is abstraction over quiet string sent by request body.

You should build a post request with query string in its body.

Let me know if it's still unclear.

**Comment by bagwaa** [comment]
Thanks for the response, admittedly I'm not 100% clear on your solution.

**Comment by pmezard** [comment]
You need to create a new HttpRequest from the input one, set its Body to the modified form string you need, and return it. Modifying the input HttpRequest in place might work for some fields, but it definitely does not work for Form : this field is constructed from the request body but updating it does not reflects on the Body (in fact the Body is probably lost at this point since it got read by ParseForm).
